### ISSUE TITLE
Simple string search gives java.lang.NullPointerException

### ISSUE THREAD

**Issue by akond** [federkasten/clucie#15]
When I try 
`(core/search index-store "beatles" 10 analyzer 0 5)`
it gives me [`java.lang.NullPointerException`. I reckon it is because of [this line here](https://github.com/federkasten/clucie/blob/master/src/clucie/core.clj#L124) which does not provide `:current-key something`, which, consequently, stumbles upon (name nil).

**Comment by totakke** [comment]
I think that is the correct behavior. Lucene field must have name and value, but

```clojure
(core/search index-store "beatles" 10 analyzer 0 5)
```

does not specify the field name of `"beatles"`.

clucie does not add a default field that contains all values, though an alternative library, [clucy](https://github.com/weavejester/clucy), implicitly prepares a default field called `_content`.

**Comment by federkasten** [comment]
Sorry for the late reply.

That exception is not a defect. Please read [the usage](https://github.com/federkasten/clucie#simple-usage) more carefully.
