### ISSUE TITLE
regexp search

### ISSUE THREAD

**Issue by vxe** [federkasten/clucie#19]
https://github.com/federkasten/clucie/blob/master/src/clucie/query.clj#L68

does this mean that regex search is implemented, or that this is a starting point for beginning to implement that functionality?

**Comment by totakke** [comment]
Regex search is not implemented by default. That is an example for extending clucie parser on the user side. If you want to use regex search, just copy and paste the example into your code.

**Comment by vxe** [comment]
awesome, thanks!
